const fs=require('fs'),vm=require('vm'),assert=require('assert');
const server={Date,Utilities:{formatDate:()=> '10.02 00:00'}};
vm.createContext(server);vm.runInContext(fs.readFileSync('dashboard_repair/WebApp.gs','utf8'),server);
assert.equal(server.wa_ticker_(10140),'010140');
assert.equal(server.wa_ticker_('000990'),'000990');
assert.equal(server.wa_keyed_([{TICKER:10140,STOP_BROKEN:true}],'TICKER')['010140'].STOP_BROKEN,true);
assert.equal(server.wa_buildAlert_({TICKER:990,CHANGE_PCT:1.1}).ticker,'000990');
assert(Math.abs(server.wa_buildAlert_({CHANGE_PCT:1.1}).changePct-110)<1e-9);
const cfg={TICKER:'010140',NAME:'삼성중공업',QTY:1013,AVG_PRICE:20119,REF_CLOSE:19960,STATUS:'ACTIVE',ENABLED:true,STOP_PRICE:21000,TARGET1:23306};
const p=server.wa_buildPosition_(cfg,{PRICE:19960,PREV_CLOSE:19720,CHANGE_PCT:0.0121703854},{});
assert.equal(p.costAmount,20380547);assert.equal(p.marketValue,20219480);
assert.equal(p.ticker,'010140');assert(Math.abs(p.changePct-1.21703854)<1e-7);
const suspended=server.wa_buildPosition_({...cfg,STATUS:'SUSPENDED_HOLD',REF_CLOSE:5310},{PRICE:0},{});
assert.equal(suspended.valuationPrice,5310);assert.equal(suspended.dayProfitLoss,null);
let banner=null;const dash={prepend:x=>{banner=x;},innerHTML:'preserved'};
const document={addEventListener:()=>{},getElementById:id=>id==='dashboard'?dash:id==='dashboardError'?banner:null,createElement:()=>({setAttribute:()=>{},remove:()=>{banner=null;}})};
const client={document,setInterval:()=>1,clearInterval:()=>{}};vm.createContext(client);vm.runInContext(fs.readFileSync('dashboard_repair/Index.script.js','utf8'),client);
assert.equal(client.won(75000),'75,000원');assert.equal(client.won(null),'-');
const html=client.stockCardHtml({...p,statusKey:'normal',statusLabel:'정상'});
assert(!html.includes('원원'));assert(html.includes('20,380,547원'));assert(!html.includes('-원'));
client.showError('connection failed');assert.equal(dash.innerHTML,'preserved');assert(banner.textContent.includes('connection failed'));
client.clearDashboardError();assert.equal(banner,null);
const calls=[];const chain={withSuccessHandler:f=>{chain.success=f;return chain;},withFailureHandler:f=>{chain.failure=f;return chain;},getDashboardData:()=>calls.push(1)};
client.google={script:{run:chain}};client.showLoading=()=>{};client.renderAll=()=>{};
client.loadDashboard();client.loadDashboard();assert.equal(calls.length,1);
chain.failure({message:'temporary'});client.loadDashboard();assert.equal(calls.length,2);
chain.success({positions:[],autoRefreshSeconds:60});assert.equal(banner,null);
assert(!/\.(setValues|setValue|clearContent|deleteRow|appendRow)\(/.test(fs.readFileSync('dashboard_repair/WebApp.gs','utf8')));
console.log('PASS: ticker joins, valuation, suspended holdings, currency, nulls, retry recovery, overlapping refresh, read-only server');
